services:
  - type: web
    name: bitcoin-ml-predictor
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_VERSION
        value: 18.20.3
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
        - server/**
        - public/**
        - tsconfig*.json